# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  version: "13.4.2"

package:
  name: "lightbug_http"
  version: 0.1.11

source:
  - path: ../lightbug_http
  - path: ../LICENSE

build:
  script:
    - mkdir -p ${PREFIX}/lib/mojo
    - magic run mojo package . -o ${PREFIX}/lib/mojo/lightbug_http.mojopkg

requirements:
  run:
    - max >=24.6.0
    - small_time == 0.1.6

about:
  homepage: https://github.com/saviorand/lightbug_http
  license: MIT
  license_file: LICENSE
  summary: Lightbug is a simple and sweet HTTP framework for Mojo
  repository: https://github.com/saviorand/lightbug_http
